smoothllm_num_copies: 8
smoothllm_perturbation_rate: 10
noise_level: 0.001
forward_batch_size: 4

defaults:
  - _self_
  - model: gemma
  - perturbation: RandomSwapPerturbation
  - metric: rouge 
  - data_format: mmlu
  - finished_task_list: mmlu
  - todo_task_list: mmlu
  - access_token: access_token