smoothllm_num_copies: 8
smoothllm_perturbation_rate: 10
noise_level: 1

defaults:
  - _self_
  - model: llama2
  - perturbation: RandomSwapPerturbation
  - metric: rouge 
  - data_format: mmlu
  - finished_task_list: mmlu
  - todo_task_list: mmlu